Api tests
engy-engy/teamcity-testing-framework pull request #1
Opened 2024-10-09 14:48 UTC by engy-engy

2024-10-12 16:02 UTC, nobugs-me approved these changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, поэтому ставлю Approve 🤝

2024-10-12 16:02 UTC, nobugs-me commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> +                .body(Matchers.containsString("You do not have \"Create subproject\" permission in project with internal id: _Root\n"
В будущем все одинаковые типы ассертов можно вынести в отдельный класс и добавлять набор ассертов как ResponseSpecification

2024-10-12 16:02 UTC, nobugs-me commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> +        user2.setRoles(generate(Roles.class, "PROJECT_ADMIN", "p:" + testData.getProject().getId()));
"PROJECT_ADMIN" можно вынести в Enum

2024-10-13 07:51 UTC, engy-engy commented
@nobugs-me Подскажи, все ли верно я понимаю, мне нужно:

1. Вмержить пулл реквест в main ветку
2. Создать новую ветку
3. В ветке отработать комментарии по ревью
4. Создать пулл-реквест и добавить тебя в качестве ревьювера.

Также хотелось бы получить комментарии по Advanced ДЗ тоже. Спасибо!

2024-10-14 12:17 UTC, nobugs-me requested changes
Привет! 

Оставила комменты по advanced заданию. 

Если хочешь доделать - нужно дождаться окончания выполнения сборки билда.

2024-10-14 12:17 UTC, nobugs-me commented on src/test/java/com/example/teamcity/api/ProjectTest.java
> +    @Test(description = "User should be able to create project", groups = {"Positive", "CRUD"})
Все хорошо реализовано с точки зрения текущих тестов, однако покрытие может быть улучшено. 🙌

Ожидаемые тест кейсы: 
1) User should be able to create a project with correct data
2) User should not be able to create a project with empty id
3) User should not be able to create a project if id starts with number
4) User should not be able to create a project if id includes invalid symbols
5) User should not be able to create a project if id cyrillic symbols
6) User should not be able to create a project if id has more than 225 symbols
7) User should not be able to create a project if id starts with _
8) User should not be able to create 2 projects with the same name
9) User should not be able to create project as Project Viewer
10) User should not be able to create project as Project Developer
11) User should not be able to create project as Agent Manager

2024-10-14 12:17 UTC, nobugs-me commented on src/test/java/com/example/teamcity/api/BuildTypeTest.java
> +        // to do checking for run build
Спасибо за выполнение advanced задания! 

Тут как раз самая "сложная" часть заключается в ожидании, когда билд пройдет.

2024-10-14 12:18 UTC, nobugs-me commented
> @nobugs-me Подскажи, все ли верно я понимаю, мне нужно:
> 
> 1. Вмержить пулл реквест в main ветку
> 2. Создать новую ветку
> 3. В ветке отработать комментарии по ревью
> 4. Создать пулл-реквест и добавить тебя в качестве ревьювера.
> 
> Также хотелось бы получить комментарии по Advanced ДЗ тоже. Спасибо!

Привет! 

Нет, нужно пофиксить все изменения в этой же ветке и снова запросить ревью.

2024-10-15 20:50 UTC, nobugs-me commented
Увидела изменения, спасибо!

2024-10-16 12:32 UTC, closed without merging